### ISSUE TITLE
Only install osxphotos if running on macOS

### ISSUE THREAD

**Issue by simonw** [dogsheep/photos-to-sqlite#17]
The build is broken right now because you can't `pip install osxphotos` on Ubuntu.

**Comment by simonw** [comment]
https://www.python.org/dev/peps/pep-0508/#environment-markers I think I want `sys_platform` of `darwin`.

**Comment by simonw** [comment]
From https://hynek.me/articles/conditional-python-dependencies/ I think this will look like:
```python
setup(
    # ...
    install_requires=[
        # ...
        "osxphotos>=0.28.13 ; sys_platform=='darwin'",
    ]
)
```

**Comment by RhetTbull** [comment]
FYI, I've got an [issue](https://github.com/RhetTbull/osxphotos/issues/25) to make osxphotos cross-platform but it's low on my priority list.  About 90% of the functionality could be done cross-platform but right now the MacOS specific stuff is embedded throughout and would take some work.  Though I try to minimize it, there's sprinklings of ObjC & Applescript throughout osxphotos.
